# Este comando informa ao Netlify para usar a versão mais recente do seu sistema de build.
[build]
  # Diretório onde estão os seus ficheiros HTML (a raiz, neste caso).
  publish = "."
  # Comando explícito para instalar as dependências Python.
  command = "pip install -r requirements.txt"

# A configuração da pasta de funções que já tínhamos.
[functions]
  directory = "netlify/functions/"

